### ISSUE TITLE
Load-Up Error

### ISSUE THREAD

**Issue by ArvickC** [ArvickC/McCore#2]
```
[11:29:47 ERROR]: Could not load 'plugins\McCore-1.0.0.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.NullPointerException
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:141) ~[patched_1.16.1.jar:git-Paper-135]
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:397) ~[patched_1.16.1.jar:git-Paper-135]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:305) ~[patched_1.16.1.jar:git-Paper-135]
        at org.bukkit.craftbukkit.v1_16_R1.CraftServer.loadPlugins(CraftServer.java:388) ~[patched_1.16.1.jar:git-Paper-135]
        at net.minecraft.server.v1_16_R1.DedicatedServer.init(DedicatedServer.java:208) ~[patched_1.16.1.jar:git-Paper-135]
        at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:941) ~[patched_1.16.1.jar:git-Paper-135]        at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Paper-135]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.NullPointerException
        at me.crazybanana.mccore.commands.staff.Mcorereload.<init>(Mcorereload.java:20) ~[?:?]
        at me.crazybanana.mccore.McCore.<init>(McCore.java:25) ~[?:?]
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:?]
        at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:490) ~[?:?]
        at java.lang.Class.newInstance(Class.java:584) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:80) ~[patched_1.16.1.jar:git-Paper-135]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:137) ~[patched_1.16.1.jar:git-Paper-135]
        ... 7 more
```

**Comment by ArvickC** [comment]
```
        at me.crazybanana.mccore.commands.staff.Mcorereload.<init>(Mcorereload.java:20) ~[?:?]
        at me.crazybanana.mccore.McCore.<init>(McCore.java:25) ~[?:?]
```

**Comment by ArvickC** [comment]
[this](https://github.com/ArvickC/McCore/commit/3167449a80676b4219a82d988fb16433b652cb6e) commit

**Comment by ArvickC** [comment]
McCore Line `25`: [found here](https://github.com/ArvickC/McCore/blob/master/src/main/java/me/crazybanana/mccore/McCore.java#L25)
McReload Line `20`: [found here](https://github.com/ArvickC/McCore/blob/8d17fd8d3548a60b2b351eef4cc8a7b3f05ac5cf/src/main/java/me/crazybanana/mccore/commands/staff/Mcorereload.java#L20)

**Comment by ArvickC** [comment]
```java
    // Var
    private McCore plugin = null;
    public String normal;

    // Constructor
    public Mcorereload(McCore plugin) {
        this.plugin = plugin;
        normal = "§" + plugin.getConfig().getString("Normal"); // Repeat for all
    }
```

**Comment by ArvickC** [comment]
https://bukkit.org/threads/tut-bukkits-new-fileconfiguration-api-create-a-yaml-configuration.42775/

**Comment by ArvickC** [comment]
solved.
